#!/bin/bash
#  _____                        __  __           _
# |  ___|__   ___ _   _ ___   |  \/  | ___   __| | ___
# | |_ / _ \ / __| | | / __|  | |\/| |/ _ \ / _` |/ _ \
# |  _| (_) | (__| |_| \__ \  | |  | | (_) | (_| |  __/
# |_|  \___/ \___|\__,_|___/  |_|  |_|\___/ \__,_|\___|
#
# Toggle focus (zen) mode for the ACTIVE workspace only.
#
# What it does:
#   • Gaps / borders / rounding → zeroed for this workspace via a workspace rule
#     (all other workspaces keep their normal layout)
#   • Waybar → hidden on ALL outputs via SIGUSR1 toggle
#     (restore on disable; purely cosmetic – other workspaces are unaffected
#     because waybar is a passive overlay and you're focused here anyway)

STATE_FILE="$HOME/.config/ml4w/settings/focusmode-enabled"
RULES_FILE="$HOME/.config/hypr/conf/focus-mode-rules.lua"

mkdir -p "$(dirname "$STATE_FILE")"

if [ -f "$STATE_FILE" ]; then
    # ── Disable ───────────────────────────────────────────────────────────────
    PREV_WS=$(cat "$STATE_FILE")
    rm -f "$STATE_FILE"

    # Clear workspace rule and reload so all original settings are restored
    printf -- "-- Focus mode rules – currently inactive\n" > "$RULES_FILE"
    hyprctl reload

    # Show waybar again (SIGUSR1 is a visibility toggle)
    pkill -SIGUSR1 waybar

    notify-send -i preferences-system "Focus mode off" \
        "Workspace $PREV_WS restored"
else
    # ── Enable ────────────────────────────────────────────────────────────────
    WS_JSON=$(hyprctl activeworkspace -j)
    WS_ID=$(echo "$WS_JSON"  | jq '.id')
    MONITOR=$(echo "$WS_JSON" | jq -r '.monitor')

    echo "$WS_ID" > "$STATE_FILE"

    # Write a workspace rule that removes all spacing for this workspace only.
    # Every other workspace keeps its gaps/borders unchanged.
    cat > "$RULES_FILE" << EOF
-- Auto-generated by focus-mode.sh — do not edit manually
hl.workspace_rule({
    workspace   = "$WS_ID",
    gaps_in     = 0,
    gaps_out    = 0,
    border_size = 0,
    no_border   = true,
    no_rounding = true,
})
EOF

    hyprctl reload

    # Hide waybar (SIGUSR1 toggles visibility; state file ensures paired restore)
    pkill -SIGUSR1 waybar

    notify-send -i preferences-system "Focus mode on" \
        "Workspace $WS_ID on $MONITOR — gaps removed, bar hidden"
fi
