# -----------------------------------------------------
# Window rules
# -----------------------------------------------------

windowrule {
    name = wr-tile-edge
    match:title = ^(Microsoft-edge)$
    tile = true
}

windowrule {
    name = wr-tile-brave
    match:title = ^(Brave-browser)$
    tile = true
}

windowrule {
    name = wr-tile-chromium
    match:title = ^(Chromium)$
    tile = true
}

windowrule {
    name = wr-float-pavucontrol
    match:title = ^(pavucontrol)$
    float = true
}

windowrule {
    name = wr-float-blueman
    match:title = ^(blueman-manager)$
    float = true
}

windowrule {
    name = wr-float-nm-editor
    match:title = ^(nm-connection-editor)$
    float = true
}

windowrule {
    name = wr-float-qalculate
    match:title = ^(qalculate-gtk)$
    float = true
}

# Browser Picture in Picture
windowrule {
    name = wr-pip
    match:title = ^(Picture-in-Picture)$
    float = true
    pin = true
    move = 69.5% 4%
    opacity = 1.0 override
}

# idleinhibit - Available modes: none, always, focus, fullscreen
windowrule {
    name = wr-idleinhibit
    match:class = [window]
    idle_inhibit = fullscreen
}

layerrule {
    name = lr-noanim-hyprpicker
    match:namespace = hyprpicker
    no_anim = true
}

layerrule {
    name = lr-noanim-selection
    match:namespace = selection
    no_anim = true
}
