git:
  pagers:
    - colorArg: always
      pager: delta --dark --pager=never --side-by-side
      externalDiffCommand: ""
  autoFetch: true
  pull:
    mode: rebase
gui:
  nerdFontsVersion: "3"
  mouseEvents: true
  showFileTree: true
  expandFocusedSidePanel: true
os:
  environment:
    BAT_STYLE: "plain"
    BAT_PAGER: "cat"
  editPreset: nvim
